application: lookaroundliugao2
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /test.*
  script: gaeunit.py

- url: /jstest
  static_dir: jsTest

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest

- name: django
  version: "1.2"

inbound_services:
- channel_presence
